// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1vszgoR9hBvjlbCijf1VhWv-SlP_qv88',
    appId: '1:593862128659:web:8f7c0031ca048c6c997be6',
    messagingSenderId: '593862128659',
    projectId: 'uts-mobile-94281',
    authDomain: 'uts-mobile-94281.firebaseapp.com',
    storageBucket: 'uts-mobile-94281.appspot.com',
    measurementId: 'G-MLDP91JP5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARv8x2VXqTVfqSSVuhs3Erqgam_GQxTcY',
    appId: '1:593862128659:android:3e0c5262614da0a0997be6',
    messagingSenderId: '593862128659',
    projectId: 'uts-mobile-94281',
    storageBucket: 'uts-mobile-94281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtZJor5M86U3LnyT4uUCQeFAloqWA0wtQ',
    appId: '1:593862128659:ios:91ccd2d5deabf935997be6',
    messagingSenderId: '593862128659',
    projectId: 'uts-mobile-94281',
    storageBucket: 'uts-mobile-94281.appspot.com',
    iosBundleId: 'com.example.flutixapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtZJor5M86U3LnyT4uUCQeFAloqWA0wtQ',
    appId: '1:593862128659:ios:43ddfd859b6c441d997be6',
    messagingSenderId: '593862128659',
    projectId: 'uts-mobile-94281',
    storageBucket: 'uts-mobile-94281.appspot.com',
    iosBundleId: 'com.example.flutixapp.RunnerTests',
  );
}
